import { YoniDefinition } from './types';

// Raw data converted from the provided CSV spec
export const YONI_DATA: YoniDefinition[] = [
  // Muladhara 1-12 (Tamas / Inert)
  { id: 1, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 64.0, vibrationHz: 28, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 2, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 68.3, vibrationHz: 29, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 3, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 72.0, vibrationHz: 30, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 4, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 76.8, vibrationHz: 31, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 5, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 80.0, vibrationHz: 32, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 6, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 85.3, vibrationHz: 33, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 7, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 90.0, vibrationHz: 34, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 8, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 96.0, vibrationHz: 35, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 9, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 102.4, vibrationHz: 36, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 10, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 106.7, vibrationHz: 37, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 11, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 115.2, vibrationHz: 38, pulseHz: 1.5, colorClass: "bg-chakra-1" },
  { id: 12, domainName: "Muladhara", levelName: "Tamas (Inert)", soundHz: 120.0, vibrationHz: 39, pulseHz: 1.5, colorClass: "bg-chakra-1" },

  // Svadhisthana 13-24 (Instinct)
  { id: 13, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 96.0, vibrationHz: 32, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 14, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 102.4, vibrationHz: 33, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 15, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 108.0, vibrationHz: 34, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 16, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 115.2, vibrationHz: 35, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 17, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 120.0, vibrationHz: 36, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 18, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 128.0, vibrationHz: 37, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 19, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 135.0, vibrationHz: 38, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 20, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 144.0, vibrationHz: 39, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 21, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 153.6, vibrationHz: 40, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 22, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 160.0, vibrationHz: 41, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 23, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 172.8, vibrationHz: 42, pulseHz: 2.5, colorClass: "bg-chakra-2" },
  { id: 24, domainName: "Svadhisthana", levelName: "Instinct", soundHz: 180.0, vibrationHz: 43, pulseHz: 2.5, colorClass: "bg-chakra-2" },

  // Manipura 25-36 (Emotion)
  { id: 25, domainName: "Manipura", levelName: "Emotion", soundHz: 128.0, vibrationHz: 36, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 26, domainName: "Manipura", levelName: "Emotion", soundHz: 136.5, vibrationHz: 37, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 27, domainName: "Manipura", levelName: "Emotion", soundHz: 144.0, vibrationHz: 38, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 28, domainName: "Manipura", levelName: "Emotion", soundHz: 153.6, vibrationHz: 39, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 29, domainName: "Manipura", levelName: "Emotion", soundHz: 160.0, vibrationHz: 40, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 30, domainName: "Manipura", levelName: "Emotion", soundHz: 170.7, vibrationHz: 41, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 31, domainName: "Manipura", levelName: "Emotion", soundHz: 180.0, vibrationHz: 42, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 32, domainName: "Manipura", levelName: "Emotion", soundHz: 192.0, vibrationHz: 43, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 33, domainName: "Manipura", levelName: "Emotion", soundHz: 204.8, vibrationHz: 44, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 34, domainName: "Manipura", levelName: "Emotion", soundHz: 213.3, vibrationHz: 45, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 35, domainName: "Manipura", levelName: "Emotion", soundHz: 230.4, vibrationHz: 46, pulseHz: 3.5, colorClass: "bg-chakra-3" },
  { id: 36, domainName: "Manipura", levelName: "Emotion", soundHz: 240.0, vibrationHz: 47, pulseHz: 3.5, colorClass: "bg-chakra-3" },

  // Anahata 37-48 (Action)
  { id: 37, domainName: "Anahata", levelName: "Action", soundHz: 192.0, vibrationHz: 40, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 38, domainName: "Anahata", levelName: "Action", soundHz: 204.8, vibrationHz: 41, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 39, domainName: "Anahata", levelName: "Action", soundHz: 216.0, vibrationHz: 42, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 40, domainName: "Anahata", levelName: "Action", soundHz: 230.4, vibrationHz: 43, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 41, domainName: "Anahata", levelName: "Action", soundHz: 240.0, vibrationHz: 44, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 42, domainName: "Anahata", levelName: "Action", soundHz: 256.0, vibrationHz: 45, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 43, domainName: "Anahata", levelName: "Action", soundHz: 270.0, vibrationHz: 46, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 44, domainName: "Anahata", levelName: "Action", soundHz: 288.0, vibrationHz: 47, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 45, domainName: "Anahata", levelName: "Action", soundHz: 307.2, vibrationHz: 48, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 46, domainName: "Anahata", levelName: "Action", soundHz: 320.0, vibrationHz: 49, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 47, domainName: "Anahata", levelName: "Action", soundHz: 345.6, vibrationHz: 50, pulseHz: 5.0, colorClass: "bg-chakra-4" },
  { id: 48, domainName: "Anahata", levelName: "Action", soundHz: 360.0, vibrationHz: 51, pulseHz: 5.0, colorClass: "bg-chakra-4" },

  // Vishuddha 49-60 (Cognition)
  { id: 49, domainName: "Vishuddha", levelName: "Cognition", soundHz: 256.0, vibrationHz: 44, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 50, domainName: "Vishuddha", levelName: "Cognition", soundHz: 273.1, vibrationHz: 45, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 51, domainName: "Vishuddha", levelName: "Cognition", soundHz: 288.0, vibrationHz: 46, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 52, domainName: "Vishuddha", levelName: "Cognition", soundHz: 307.2, vibrationHz: 47, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 53, domainName: "Vishuddha", levelName: "Cognition", soundHz: 320.0, vibrationHz: 48, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 54, domainName: "Vishuddha", levelName: "Cognition", soundHz: 341.3, vibrationHz: 49, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 55, domainName: "Vishuddha", levelName: "Cognition", soundHz: 360.0, vibrationHz: 50, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 56, domainName: "Vishuddha", levelName: "Cognition", soundHz: 384.0, vibrationHz: 51, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 57, domainName: "Vishuddha", levelName: "Cognition", soundHz: 409.6, vibrationHz: 52, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 58, domainName: "Vishuddha", levelName: "Cognition", soundHz: 426.7, vibrationHz: 53, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 59, domainName: "Vishuddha", levelName: "Cognition", soundHz: 460.8, vibrationHz: 54, pulseHz: 6.5, colorClass: "bg-chakra-5" },
  { id: 60, domainName: "Vishuddha", levelName: "Cognition", soundHz: 480.0, vibrationHz: 55, pulseHz: 6.5, colorClass: "bg-chakra-5" },

  // Ajna 61-72 (Wisdom)
  { id: 61, domainName: "Ajna", levelName: "Wisdom", soundHz: 384.0, vibrationHz: 48, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 62, domainName: "Ajna", levelName: "Wisdom", soundHz: 409.6, vibrationHz: 49, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 63, domainName: "Ajna", levelName: "Wisdom", soundHz: 432.0, vibrationHz: 50, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 64, domainName: "Ajna", levelName: "Wisdom", soundHz: 460.8, vibrationHz: 51, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 65, domainName: "Ajna", levelName: "Wisdom", soundHz: 480.0, vibrationHz: 52, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 66, domainName: "Ajna", levelName: "Wisdom", soundHz: 512.0, vibrationHz: 53, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 67, domainName: "Ajna", levelName: "Wisdom", soundHz: 540.0, vibrationHz: 54, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 68, domainName: "Ajna", levelName: "Wisdom", soundHz: 576.0, vibrationHz: 55, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 69, domainName: "Ajna", levelName: "Wisdom", soundHz: 614.4, vibrationHz: 56, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 70, domainName: "Ajna", levelName: "Wisdom", soundHz: 640.0, vibrationHz: 57, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 71, domainName: "Ajna", levelName: "Wisdom", soundHz: 691.2, vibrationHz: 58, pulseHz: 8.0, colorClass: "bg-chakra-6" },
  { id: 72, domainName: "Ajna", levelName: "Wisdom", soundHz: 720.0, vibrationHz: 59, pulseHz: 8.0, colorClass: "bg-chakra-6" },

  // Sahasrara 73-84 (Liberated)
  { id: 73, domainName: "Sahasrara", levelName: "Liberated", soundHz: 512.0, vibrationHz: 52, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 74, domainName: "Sahasrara", levelName: "Liberated", soundHz: 546.1, vibrationHz: 53, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 75, domainName: "Sahasrara", levelName: "Liberated", soundHz: 576.0, vibrationHz: 54, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 76, domainName: "Sahasrara", levelName: "Liberated", soundHz: 614.4, vibrationHz: 55, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 77, domainName: "Sahasrara", levelName: "Liberated", soundHz: 640.0, vibrationHz: 56, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 78, domainName: "Sahasrara", levelName: "Liberated", soundHz: 682.7, vibrationHz: 57, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 79, domainName: "Sahasrara", levelName: "Liberated", soundHz: 720.0, vibrationHz: 58, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 80, domainName: "Sahasrara", levelName: "Liberated", soundHz: 768.0, vibrationHz: 59, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 81, domainName: "Sahasrara", levelName: "Liberated", soundHz: 819.2, vibrationHz: 60, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 82, domainName: "Sahasrara", levelName: "Liberated", soundHz: 853.3, vibrationHz: 61, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 83, domainName: "Sahasrara", levelName: "Liberated", soundHz: 921.6, vibrationHz: 62, pulseHz: 9.5, colorClass: "bg-chakra-7" },
  { id: 84, domainName: "Sahasrara", levelName: "Liberated", soundHz: 960.0, vibrationHz: 63, pulseHz: 9.5, colorClass: "bg-chakra-7" },
];